### ISSUE TITLE
v7 can not support minetest 5.3.0

### ISSUE THREAD

**Issue by Pevernow** [minetest-tools/mtmediasrv#3]
It always return "Invalid GET from ........".
Test server: 45.195.153.173:30000
Test mtmediasrv: http://45.195.153.173:30000

**Comment by sofar** [comment]
How do you test it? what exactly are the logs? how did you configure it?

**Comment by Pevernow** [comment]
I try to connect to the server and then open the network monitor, which shows minetest.exe Only the UDP port is established and there is no TCP connection.

The configuration is almost the same as the default, I only modified the sock path and resource path.
Use nginx

**Comment by sofar** [comment]
The media server I run at media.foo-projects.org (using mtmediasrv) is seeing plenty of successful minetest 5.3.0 clients connect and provide the index data. 

You must have misconfigured your minetest server, nginx, or mtmediasrv. Without seeing the exact configs/logs/output of all of those, I can't help.

**Comment by Pevernow** [comment]
It may be my config is wrong.But can we migrate mtmediasrv to cloudflare worker?

**Comment by sofar** [comment]
I don't know the capabilities of a cloudflare worker, so I can't answer that question.
